//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netflix
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public video()
        {
            this.favorite_videos = new HashSet<favorite_videos>();
            this.playlist_video = new HashSet<playlist_video>();
        }
    
        public int video_id { get; set; }
        public string video_name { get; set; }
        public Nullable<int> video_time { get; set; }
        public string video_rel_country { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public string director { get; set; }
        public string writers { get; set; }
        public string stars { get; set; }
        public Nullable<double> rating { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorite_videos> favorite_videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<playlist_video> playlist_video { get; set; }
    }
}
