//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netflix.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string account_type { get; set; }
    
        public virtual user user { get; set; }
    }
}
